select ?node ?nlabel ?prop ?plabel ?value ?xref where {
    ?node s223:hasProperty ?prop .
    ?prop a s223:Property .
    optional { ?node rdfs:label ?nlabel } .
    optional { ?prop rdfs:label ?plabel } .
    optional { ?prop s223:hasValue ?value } .
    optional { ?prop s223:hasExternalReference ?xref } .
    }
