# SERVISYS inc. Gitlab-CI Configuration file
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python3 -V # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install .
  - pip install pytest
  - pip install pyshacl
  - pip install ontoenv
  - pip install rdflib
  - pip install pyvis

test_python:
  script:
    - pytest

generate_html:
  script:
    - rdf2html samples/ttl
    - rdf2html G36/ttl
  artifacts:
    paths:
      - samples/ttl/*.html
      - G36/ttl/*.html

validate:
  image: docker:latest
  services:
    - docker:dind
  before_script: []
  script:
    - apk add --no-cache git python3 py3-pip  # Install necessary packages
    - docker build --tag validate:latest --file topbraid-validate/validate.dockerfile .
    - git clone https://bas-im.emcs.cornell.edu/223/223standard
    - export S223_FOLDER=$(pwd)/223standard
    - python3 topbraid-validate/merge-graphs.py --no-imports --clean $S223_FOLDER/models/*.ttl $S223_FOLDER/vocab/*.ttl $S223_FOLDER/validation/*.ttl $S223_FOLDER/inference/*.ttl $S223_FOLDER/imports/qudt/VOCAB_QUDT-QUANTITY-KINDS-ALL-v2.1.ttl $S223_FOLDER/imports/qudt/VOCAB_QUDT-UNITS-ALL-v2.1.ttl 223standard.ttl
    - mv 223standard.ttl samples/validation
    - for data_file in samples/ttl/validation/*.data.ttl; do
        prefix=$(basename "$data_file" .data.ttl);
        schema_file="samples/ttl/validation/${prefix}.schema.ttl";
        if [ -f "$schema_file" ]; then
          validate-run.sh "$data_file" "$schema_file";
        else
          echo "Schema file $schema_file not found for data file $data_file";
        fi;
      done
  artifacts:
    paths: ['samples/validation/223standard.ttl']
  when: manual
