select ?node ?prop ?label ?comment where {
    ?node s223:hasDomain s223:Domain-HVAC .
    ?node s223:hasProperty ?prop .
    optional { ?prop rdfs:label ?label } .
    optional { ?prop rdfs:comment ?comment } .
    }
