[project]
name = "bob"
version = "0.98"
authors = [
    {name="Joel Bender", email="jjb5@cornell.edu"},
    {name="Christian Tremblay", email="christian.tremblay@servisys.com"},
]
description = "Bob the SI-WG Builder. Tool for building RDF graphs of HVAC systems"
readme = "README.md"
license = {text = "MIT"}
dependencies = [
    "rdflib",
    "python-dotenv",
    
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["bob*", "rdf2html", "ttl_tools"]
namespaces = false

[project.optional-dependencies]
test = ["pytest", "pyshacl", "ontoenv", "pyvis", "click"]
lint = ["black", "flake8", "isort"]
cov = ["pytest < 5.0.0", "pytest-cov[all]"]

[project.scripts]
rdf2html = "rdf2html.rdf2html:process"
mergegraphs = "ttl_tools.mergegraphs:main"
compile_ttl = "ttl_tools.compile:main"
validation2html = "ttl_tools.validation2html:main"
query_model = "ttl_tools.query_model:main"
