[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "bob"
version = "0.81"
authors = [
    {name="Joel Bender", email="jjb5@cornell.edu"},
    {name="Christian Tremblay", email="christian.tremblay@servisys.com"},
]
description = "Bob the SI-WG Builder. Tool for building RDF graphs of HVAC systems"
readme = "README.md"
license = {text = "MIT"}
dependencies = [
    "rdflib",
    "importlib-metadata",
    "brickschema"
]

[project.optional-dependencies]
test = ["pytest", "pyshacl", "ontoenv", "pyvis", "click"]
lint = [ "black", "flake8", "isort"]
cov = ["pytest < 5.0.0", "pytest-cov[all]"]

[tool.setuptools_scm]
# write_to = "bob/_version.py"

[tool.setuptools]
packages = [
    "bob",
    "tools",
    ]
[project.scripts]
rdf2html = "tools.rdf2html:process"
