[project]
name = "bob"
version = "0.88"
authors = [
    {name="Joel Bender", email="jjb5@cornell.edu"},
    {name="Christian Tremblay", email="christian.tremblay@servisys.com"},
]
description = "Bob the SI-WG Builder. Tool for building RDF graphs of HVAC systems"
readme = "README.md"
license = {text = "MIT"}
dependencies = [
    "rdflib",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["bob*"]
namespaces = false

[project.optional-dependencies]
test = ["pytest", "pyshacl", "ontoenv", "pyvis", "click"]
lint = ["black", "flake8", "isort"]
cov = ["pytest < 5.0.0", "pytest-cov[all]"]

