#!/bin/bash

python validate.py samples/ttl/sample_pritoni_model.data.ttl \
    --ontology samples/ttl/sample_pritoni_model.schema.ttl \
    --s223-sparql-rule --clean --both \
    --expanded cj.ttl \
    --inference cj.inference.ttl \
    --report cj.rpt.ttl
