#!/bin/bash

python validate.py ~/bacnet-si-wg/223standard/data/nonconforming/pd-sr-mp-pritoni.ttl \
    --both --clean \
    --expanded psm.ttl \
    --inference psm.inference.ttl \
    --report psm.rpt.ttl
