PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX s223: <http://data.ashrae.org/standard223#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?nodeLabel ?propLabel ?p ?o
WHERE {
    ?prop a s223:Property .
    ?prop s223:hasExternalReference ?extRef .
    ?prop rdfs:label ?propLabel .
    ?extRef ?p ?o .
    ?node s223:hasProperty ?prop .
    ?node rdfs:label ?nodeLabel .
}
