# Last modified 2022-05-11
# Displays all unoccupied rooms that have TemperatureSensors, with the average, min and max (current) readings per room.
# Model differences:
# 1. PD model uses s223:OccupancyStatus-Unoccupied. JB model uses s223:Occupancy-Unoccupied
# 2. JB model has no physical spaces enclosing the relevant domain spaces
# 3. The JB model attaches occupancy properties to function blocks, which is not conformant.
PREFIX s223: <http://data.ashrae.org/standard223#>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX qudtqk: <http://qudt.org/vocab/quantitykind/>
#PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?roomLabel (AVG(?tval) AS ?avg)
WHERE {
?oprop a/rdfs:subClassOf* s223:Property .
?oprop s223:hasValue s223:OccupancyStatus-Unoccupied .
?ds s223:hasProperty ?oprop .
?room s223:encloses ?ds .
?room s223:encloses ?otherds .
?otherds s223:hasProperty ?tprop .
?tprop qudt:hasQuantityKind qudtqk:Temperature .
?tprop s223:hasValue ?tval .
?room rdfs:label ?roomLabel .
}
GROUP BY ?roomLabel
