"""
Sort a turtle file generated by rdflib.
"""

import sys
import os
import subprocess

directory = "ttl"


for filename in os.scandir(os.path.join(os.getcwd(), "LBNL-FDD")):
    if filename.name == "LBNL-FDD":
        continue
    if filename.name.startswith("LBNL"):
        print("Making TTL")
        print(filename.path)
        subprocess.call(["python", filename.path])
