"""
Sort a turtle file generated by rdflib.
"""

import hashlib
import os
import pickle
import subprocess
import sys

directory = "samples/ttl"
hash_file = "samples/ttl/ttl_hash.db"  # detect changes so we don't recreate HTML when no needed.


def calc_hash(file):
    file_hash = hashlib.sha256()
    with open(file, "rb") as f:
        fb = f.read()
        file_hash.update(fb)

    return file_hash.hexdigest()


try:
    with open(hash_file, "rb") as f:
        existing_hash = pickle.load(f)
except FileNotFoundError:
    existing_hash = {}
new_hash_dict = {}

for filename in os.scandir(os.path.join(os.getcwd(), directory)):
    print(filename)
    if filename.name == "samples":
        continue
    if filename.name.endswith(".ttl"):
        print("Making HTML files")
        print(filename.path)
        new_hash_dict[filename.path] = calc_hash(filename.path)
        if new_hash_dict[filename.path] == existing_hash.get(filename.path, ""):
            pass
        else:
            print("File is different")
            subprocess.run(["python", "bob/tools/rdf2html.py", filename.path])

    with open(hash_file, "wb") as f:
        pickle.dump(new_hash_dict, f)
