"""
Sort a turtle file generated by rdflib.
"""

import sys
import os
import subprocess

directory = "ttl"


for filename in os.scandir(os.path.join(os.getcwd(), "samples")):
    if filename.name == "samples":
        continue
    if filename.name.startswith("sample"):
        print("Making TTL")
        print(filename.path)
        subprocess.call(["python", filename.path])
