"""
Sort a turtle file generated by rdflib.
"""

import sys
import os
import subprocess

directory = "ttl"


if __name__ == "__main__":
    # iterate over files in
    # that directory
    for filename in os.scandir(os.getcwd()):
        if filename.name.startswith("sample"):
            print("Making TTL")
            print(filename.path)
            subprocess.call(["python", filename.path])
