"""
Sort a turtle file generated by rdflib.
"""

import os
import subprocess
import sys

directory = "samples/ttl"


for filename in os.scandir(os.path.join(os.getcwd(), directory)):
    print(filename)
    if filename.name == "samples":
        continue
    if filename.name.endswith(".ttl"):
        print("Making HTML files")
        print(filename.path)
        subprocess.call(["python", "./rdf2html.py", filename.path])
